export const FETCH_LINKS_START = "FETCH_LINKS_START";
export const FETCH_LINKS_SUCCESS = "FETCH_LINKS_SUCCESS";
export const FETCH_LINKS_FAIL = "FETCH_LINKS_FAIL";

export const FETCH_TRENDING_START = "FETCH_TRENDING_START";
export const FETCH_TRENDING_SUCCESS = "FETCH_TRENDING_SUCCESS";
export const FETCH_TRENDING_FAIL = "FETCH_TRENDING_FAIL";

export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";

export const FETCH_SEARCH_PRODUCT_START = "FETCH_SEARCH_PRODUCT_START";
export const FETCH_SEARCH_PRODUCT_SUCCESS = "FETCH_SEARCH_PRODUCT_SUCCESS";
export const FETCH_SEARCH_PRODUCT_FAIL = "FETCH_SEARCH_PRODUCT_FAIL";

export const FETCH_SIZES_PRODUCT_START = "FETCH_SIZES_PRODUCT_START";
export const FETCH_SIZES_PRODUCT_SUCCESS = "FETCH_SIZES_PRODUCT_SUCCESS";
export const FETCH_SIZES_PRODUCT_FAIL = "FETCH_SIZES_PRODUCT_FAIL";

export const FETCH_RATINGS_PRODUCT_START = "FETCH_RATINGS_PRODUCT_START";
export const FETCH_RATINGS_PRODUCT_SUCCESS = "FETCH_RATINGS_PRODUCT_SUCCESS";
export const FETCH_RATINGS_PRODUCT_FAIL = "FETCH_RATINGS_PRODUCT_FAIL";

export const SORT_REVIEWS_NEWEST = "SORT_REVIEWS_NEWEST"
export const SORT_REVIEWS_HELPFUL = "SORT_REVIEWS_HELPFUL"
export const SORT_REVIEWS_RELEVANT = "SORT_REVIEWS_RELEVANT"

export const FETCH_REVIEWS_PRODUCT_START = "FETCH_REVIEWS_PRODUCT_START";
export const FETCH_REVIEWS_PRODUCT_SUCCESS = "FETCH_REVIEWS_PRODUCT_SUCCESS";
export const FETCH_REVIEWS_PRODUCT_FAIL = "FETCH_REVIEWS_PRODUCT_FAIL";

export const FETCH_FILTER_LINKS_START = "FETCH_FILTER_LINKS_START";
export const FETCH_FILTER_LINKS_SUCCESS = "FETCH_FILTER_LINKS_SUCCESS";
export const FETCH_FILTER_LINKS_FAIL = "FETCH_FILTER_LINKS_FAIL";

export const FETCH_PRODUCT_ITEMS_START = "FETCH_PRODUCT_ITEMS_START";
export const FETCH_PRODUCT_ITEMS_SUCCESS = "FETCH_PRODUCT_ITEMS_SUCCESS";
export const FETCH_PRODUCT_ITEMS_FAIL = "FETCH_PRODUCT_ITEMS_FAIL";

export const GO_BACK_PAGE = "GO_BACK_PAGE";
export const GO_FORWARD_PAGE = "GO_FORWARD_PAGE";
export const RESET_TO_FIRST_PAGE = "RESET_TO_FIRST_PAGE";