export const FETCH_LINKS_START = "FETCH_LINKS_START";
export const FETCH_LINKS_SUCCESS = "FETCH_LINKS_SUCCESS";
export const FETCH_LINKS_FAIL = "FETCH_LINKS_FAIL";

export const FETCH_TRENDING_START = "FETCH_TRENDING_START";
export const FETCH_TRENDING_SUCCESS = "FETCH_TRENDING_SUCCESS";
export const FETCH_TRENDING_FAIL = "FETCH_TRENDING_FAIL";